#pragma once

// Dependencies | glew
#include <glew/glew.h>

// Dependencies | glfw
#include <glfw/glfw3.h>

namespace gl {
	enum class DataType {
		// Default
		NONE = -1,

		// Scalars
		BOOL = GL_BOOL,
		BYTE = GL_BYTE,
		SHORT = GL_SHORT,
		INT = GL_INT,
		UNSIGNED_INT = GL_UNSIGNED_INT,
		FLOAT = GL_FLOAT,
		DOUBLE = GL_DOUBLE,
		FIXED = GL_FIXED,

		// vec2
		BOOL_VEC2 = GL_BOOL_VEC2,
		INT_VEC2 = GL_INT_VEC2,
		UNSIGNED_INT_VEC2 = GL_UNSIGNED_INT_VEC2,
		FLOAT_VEC2 = GL_FLOAT_VEC2,
		DOUBLE_VEC2 = GL_DOUBLE_VEC2,
		
		// vec3
		BOOL_VEC3 = GL_BOOL_VEC3,
		INT_VEC3 = GL_INT_VEC3,
		UNSIGNED_INT_VEC3 = GL_UNSIGNED_INT_VEC3,
		FLOAT_VEC3 = GL_FLOAT_VEC3,
		DOUBLE_VEC3 = GL_DOUBLE_VEC3,
		
		// vec4
		BOOL_VEC4 = GL_BOOL_VEC4,
		INT_VEC4 = GL_INT_VEC4,
		UNSIGNED_INT_VEC4 = GL_UNSIGNED_INT_VEC4,
		FLOAT_VEC4 = GL_FLOAT_VEC4,
		DOUBLE_VEC4 = GL_DOUBLE_VEC4,

		// mat2
		FLOAT_MAT2 = GL_FLOAT_MAT2,
		DOUBLE_MAT2 = GL_DOUBLE_MAT2,
		
		// mat3
		FLOAT_MAT3 = GL_FLOAT_MAT3,
		DOUBLE_MAT3 = GL_DOUBLE_MAT3,
		
		// mat4
		FLOAT_MAT4 = GL_FLOAT_MAT4,
		DOUBLE_MAT4 = GL_DOUBLE_MAT4,
		
		// mat2x3
		FLOAT_MAT2x3 = GL_FLOAT_MAT2x3,
		DOUBLE_MAT2x3 = GL_DOUBLE_MAT2x3,
		
		// mat2x4
		FLOAT_MAT2x4 = GL_FLOAT_MAT2x4,
		DOUBLE_MAT2x4 = GL_DOUBLE_MAT2x4,
		
		// mat3x2
		FLOAT_MAT3x2 = GL_FLOAT_MAT3x2,
		DOUBLE_MAT3x2 = GL_DOUBLE_MAT3x2,
		
		// mat3x4
		FLOAT_MAT3x4 = GL_FLOAT_MAT3x4,
		DOUBLE_MAT3x4 = GL_DOUBLE_MAT3x4,
		
		// mat4x2
		FLOAT_MAT4x2 = GL_FLOAT_MAT4x2,
		DOUBLE_MAT4x2 = GL_DOUBLE_MAT4x2,
		
		// mat4x3
		FLOAT_MAT4x3 = GL_FLOAT_MAT4x3,
		DOUBLE_MAT4x3 = GL_DOUBLE_MAT4x3
	};
}
